//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace form_controls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class borrowed
    {
        public int ID { get; set; }
        public string memb_no { get; set; }
        public string isbn { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual book book { get; set; }
    }
}
