//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace form_controls.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exercise7
    {
        public string memb_no { get; set; }
        public string name { get; set; }
    }
}
